ecs.system("move", { "Position" }, function(entity, components, dt)
    local x = components.Position:readFloat("x")
    local y = components.Position:readFloat("y")
    components.Position:writeFloat("x", x + dt * 10)
    components.Position:writeFloat("y", y + dt * 10)
end)
